kind: pipeline
type: docker
name: default

steps:
  - name: build and push multi-platform image
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    settings:
      registry: 
        from_secret: REGISTRY_URL
      repo: registry.yewolf.fr/yyewolf/portfolio
      buildx: true
      platforms:
        - linux/amd64
        - linux/arm64
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD
      auto_tag: true
