// Lesson 9's packing rounds, as data.
//
// Four applications, each a handful of processes, and for each one the reader
// decides which processes share a pod. The rounds carry no verdicts and no
// explanations: every sentence the reader gets back is generated by engine.ts
// from the arrangement they built, so a mistake nobody anticipated still gets a
// truthful answer instead of silence.
//
// Each round is built so that exactly one rule decides it, and the temptation
// is always the same one: these processes belong to the same application, so
// they feel like they belong in the same pod. Belonging to an application is
// not the test. Sharing a lifetime, a machine, an address and a set of files
// is.
//
// Vocabulary: lesson 9 owns pod, container, init container and volume-as-a-
// directory. It may not explain Deployments, Jobs, Services, probes or
// scheduling; where a finding brushes one it says what happens, never its name.

/** A process the reader has to place. One process becomes one container. */
export interface Proc {
  id: string;
  /** Container name. Appears in the generated YAML. */
  name: string;
  image: string;
  /** One line, written the way the team who owns it would say it. */
  what: string;
  /** How many of this the system needs running. */
  copies: number;
  /** Runs to completion and exits, rather than staying up. */
  oneshot?: boolean;
  /** Ids it connects to on 127.0.0.1. */
  localhost?: string[];
  /** The port it binds, if it binds one. */
  port?: number;
}

/** A directory two or more processes need to be the same directory. */
export interface Share {
  name: string;
  path: string;
  members: string[];
}

export interface Round {
  n: number;
  title: string;
  /** The situation, as the team would describe it. */
  brief: string;
  procs: Proc[];
  shares?: Share[];
  /** Pods the reader can place into. Two is enough for every round here. */
  pods: string[];
  /** Whether the "before the others start" slot is offered. */
  init: boolean;
  /** One line under the generated YAML once the round is solved. */
  note: string;
}

export const rounds: Round[] = [
  {
    n: 1,
    title: "A web front end and its cache",
    brief:
      "Three copies of the front end, because that's what takes the traffic. One Redis, holding the rendered pages all three of them read.",
    pods: ["a", "b"],
    init: false,
    procs: [
      {
        id: "web",
        name: "web",
        image: "shop/web:2.9",
        what: "Serves the site. Looks up rendered pages in Redis before building them.",
        copies: 3,
        port: 80,
      },
      {
        id: "cache",
        name: "cache",
        image: "redis:7.2",
        what: "Holds the rendered pages. One store, so a page only ever gets built once.",
        copies: 1,
        port: 6379,
      },
    ],
    note: "Two pods, because you want three of one thing and one of the other.",
  },

  {
    n: 2,
    title: "An API and its log shipper",
    brief:
      "The API writes a request log to /var/log/api. The shipper tails that file and forwards each line to the log service. Four copies of the API, and every copy's log has to reach the shipper.",
    pods: ["a", "b"],
    init: false,
    shares: [{ name: "logs", path: "/var/log/api", members: ["api", "shipper"] }],
    procs: [
      {
        id: "api",
        name: "api",
        image: "shop/api:4.1",
        what: "Serves the API. Appends every request to /var/log/api/access.log.",
        copies: 4,
        port: 8080,
      },
      {
        id: "shipper",
        name: "shipper",
        image: "fluent-bit:3.0",
        what: "Tails /var/log/api and forwards the lines. Needs one of itself per copy of the API.",
        copies: 4,
      },
    ],
    note: "One pod, two containers, one directory between them.",
  },

  {
    n: 3,
    title: "An API behind TLS, and the docs site",
    brief:
      "The API binds 127.0.0.1:8080 and refuses anything that did not come from its own machine. The proxy terminates TLS on 443 and forwards inwards. The docs site is a pile of static HTML that talks to nothing, and it also serves on 8080.",
    pods: ["a", "b"],
    init: false,
    procs: [
      {
        id: "api",
        name: "api",
        image: "shop/api:4.1",
        what: "Binds 127.0.0.1:8080. Will not accept a connection from any other address.",
        copies: 3,
        port: 8080,
      },
      {
        id: "proxy",
        name: "proxy",
        image: "envoy:1.31",
        what: "Terminates TLS on 443 and forwards to 127.0.0.1:8080.",
        copies: 3,
        localhost: ["api"],
        port: 443,
      },
      {
        id: "docs",
        name: "docs",
        image: "shop/docs:1.0",
        what: "Static documentation on 8080. Talks to nothing and is read by almost nobody.",
        copies: 1,
        port: 8080,
      },
    ],
    note: "The same rule that puts two of these together is the one that keeps the third out.",
  },

  {
    n: 4,
    title: "Config on the way up, and a report at night",
    brief:
      "Before the worker can serve anything it needs the current config bundle in /etc/worker, fetched fresh at start. Separately, one report runs at 03:00, reads the database, writes a file to object storage and exits.",
    pods: ["a", "b"],
    init: true,
    shares: [{ name: "config", path: "/etc/worker", members: ["fetch", "worker"] }],
    procs: [
      {
        id: "worker",
        name: "worker",
        image: "shop/worker:6.0",
        what: "Reads /etc/worker at startup and then stays up serving. Four copies.",
        copies: 4,
        port: 8080,
      },
      {
        id: "fetch",
        name: "fetch-config",
        image: "shop/configctl:2.2",
        what: "Downloads the config bundle into /etc/worker, then exits. Takes about four seconds.",
        copies: 4,
        oneshot: true,
      },
      {
        id: "report",
        name: "report",
        image: "shop/reports:3.4",
        what: "Runs once at 03:00, reads the database over the network, writes a file and exits.",
        copies: 1,
        oneshot: true,
      },
    ],
    note: "Both of these exit when they're done, but only one of them belongs inside the worker's lifetime.",
  },
];
